account/urls.py
from django.urls import path

from .views import (
    user_view,
    edit_user_view,
)

app_name = 'account'

urlpatterns = [
    path('<username>/', user_view, name="view"),
    path('<username>/edit/', edit_user_view, name="edit"),
]

backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from .views import home_view
from account.views import (
    login_view,
    logout_view,
    register_view
)

urlpatterns = [
    path('', home_view, name='home'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),

    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('register/', register_view, name="register"),

    # Password reset links
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='password_reset/password_change_done.html'), name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='password_reset/password_change.html'), name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset/password_reset_complete.html'),name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/snippets/footer.html
{% load static %}

<footer>
    <div class="footer_section"><h4>title</h4><p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolore reprehenderit similique ad. Alias culpa ipsum repudiandae porro commodi dolore praesentium aspernatur. Labore quasi eum aut nisi maxime nam nobis obcaecati.</p></div>
    <div class="footer_section"><h4>title</h4><p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolore reprehenderit similique ad. Alias culpa ipsum repudiandae porro commodi dolore praesentium aspernatur. Labore quasi eum aut nisi maxime nam nobis obcaecati.</p></div>
    <div class="footer_section"><h4>title</h4><p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolore reprehenderit similique ad. Alias culpa ipsum repudiandae porro commodi dolore praesentium aspernatur. Labore quasi eum aut nisi maxime nam nobis obcaecati.</p></div>
</footer>

<!-- END Footer -->

templates/snippets/header.html
{% load static %}
<nav class="navbar_container">
  <div class="nav_brand">
    <a class="nav_text" href="{% url 'home' %}">
      <img
        class="nav_logo logo_img"
        src="{% static 'images/logo/black-100@2x.png' %}"
    /></a>
  </div>
  <div class="collapse" id="collapse">
    <ul class="links_area">
      <li class="nav_link tooltip">
        <h4 class="tooltiptext">Home</h4>
        <a href="{% url 'home' %}"
          ><img
            class="nav_icon"
            src="{% static 'images/icon/home-24px.svg' %}"
            alt="search"
          />
        </a>
      </li>
      <li class="nav_link tooltip">
        <h4 class="tooltiptext">Learning path</h4>
        <a href="#" style="font-size: 11px"
          ><img
            class="nav_icon"
            src="{% static 'images/icon/route.svg' %}"
            alt="search"
        /></a>
      </li>
      <li class="nav_link tooltip">
        <h4 class="tooltiptext">Course</h4>
        <a href="#"
          ><img
            class="nav_icon"
            src="{% static 'images/icon/education.svg' %}"
            alt="search"
        /></a>
      </li>
      {% if request.user.is_authenticated %} {% if request.user.is_superuser %}
      <li class="nav_link tooltip">
        <h4 class="tooltiptext">Admin dashboard</h4>
        <a href="#"
          ><img
            class="nav_icon"
            src="{% static 'images/icon/admin_panel_settings-black-18dp.svg' %}"
            alt="search"
        /></a>
      </li>
      {% elif request.user.is_staff %}
      <li class="nav_link tooltip">
        <h4 class="tooltiptext">Teacher dashboard</h4>
        <a href="#"
          ><img
            class="nav_icon"
            src="{% static 'images/icon/teacher.svg' %}"
            alt="search"
          />Dashboard</a
        >
      </li>
      {% else %}
      <li class="nav_link tooltip">
        <h4 class="tooltiptext">Student dashboard</h4>
        <a href="#"
          ><img
            class="nav_icon"
            src="{% static 'images/icon/graduated.svg' %}"
            alt="search"
        /></a>
      </li>
      {% endif %} {% endif %}
      <li class="nav_link dropdown">
        <a href="#"
          ><img
            class="nav_icon"
            src="{% static 'images/icon/search-black-18dp.svg' %}"
            alt="search"
        /></a>
        <ul class="dropdown_content" id="dropdown_content_search">
          <li><input type="text">
          </li>
          <li><a href="#"
            ><img
              class="nav_icon"
              src="{% static 'images/icon/search-white-18dp.svg' %}"
              alt="search"
          /></a></li>
        </ul>
      </li>
    </ul>
  </div>
  <div class="nav_btn">
    <ul class="links_area">
      {% if request.user.is_authenticated %}
      <li class="nav_link dropdown">
        <a href="{% url 'account:view' username=request.user.username %}"
          ><img
            class="nav_icon"
            src="{% static 'images/icon/person-black-18dp.svg' %}"
            alt="search"
        /></a>
        <ul class="dropdown_content">
          <li>
            <a
              class=""
              href="{% url 'account:edit' username=request.user.username %}"
              >Edit profile</a
            >
          </li>
          <li>
            <a class="" href="{% url 'logout' %}">Logout</a>
          </li>
        </ul>
      </li>
      <li class="nav_link">
        <a href="#"
          ><img
            class="nav_icon"
            src="{% static 'images/icon/notifications-24px.svg' %}"
            alt="search"
        /></a>
      </li>
      <li class="nav_link">
        <a href="#"
          ><img
            class="nav_icon"
            src="{% static 'images/icon/email-24px.svg' %}"
            alt="search"
        /></a>
      </li>
      {% else %}
      <li class="nav_link tooltip">
        <h4 class="tooltiptext">Login</h4>
        <a href="{% url 'login' %}"
          ><img
            class="nav_icon"
            src="{% static 'images/icon/login-black-18dp.svg' %}"
            alt="search"
        /></a>
      </li>
      <li class="nav_link tooltip">
        <h4 class="tooltiptext">Register</h4>
        <a href="{% url 'register' %}"
          ><img
            class="nav_icon"
            src="{% static 'images/icon/person_add-24px.svg' %}"
            alt="search"
        /></a>
      </li>
      {% endif %}
      <li class="nav_link open" id="menu"><a id="" class="" href="#"></a></li>
    </ul>
  </div>
</nav>
<!-- END header -->

templates/snippets/warning.html
{% load static %}

<!-- Warning -->
<div id="warning"></div>

<!-- END warning -->